name: Python Tests

on: [push, pull_request]

jobs:
  test:
    name: Python tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Clear pip cache
        run: |
          pip cache purge

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug environment
        run: |
          python --version
          pip --version
          pip list

      - name: Run tests with retry
        run: |
          RETRY_LIMIT=3
          COUNT=0
          until [ $COUNT -ge $RETRY_LIMIT ]
          do
            pytest ./tests && break
            COUNT=$((COUNT+1))
            echo "Tests failed. Retrying... ($COUNT/$RETRY_LIMIT)"
            sleep 5  # Optional: Delay before retry
          done
